
# **<font color='blue'>panData</font>**
# **<font color='blue'>Data Analysis Projects with Python Language</font>**
# **<font color='blue'>Data Cleaning and Handling Techniques for Missing Values in Data Analysis</font>**
# **<font color='blue'>Part 2</font>**

# **Python Packages Used in the Project**

In [379]:
!pip install -q -U watermark

In [380]:
# 1. Imports
import math
import sys, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import warnings
warnings.filterwarnings('ignore')

In [381]:
%reload_ext watermark
%watermark -a "panData"

Author: panData

## **Loading the Data**

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [382]:
# 2. We create a list to identify missing values
missing_values_labels_list = ["n/a", "na", "undefined"]

In [383]:
# 3. Load the dataset
dataset = pd.read_csv("dataset.csv", na_values=missing_values_labels_list)

In [384]:
# 4. Shape
dataset.shape

(150001, 55)

In [385]:
# 5. Data Sample
dataset.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [386]:
# 6. Set the total number of columns to display when printing the dataframe
pd.set_option('display.max_columns', 100)

In [387]:
# 7. Data Sample
dataset.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [388]:
# 8. Loading the Data Dictionary
data_dictionary = pd.read_excel("dictionary.xlsx")

In [389]:
# 9. Shape
data_dictionary.shape

(56, 2)

In [390]:
# 10. Data Sample
data_dictionary.head(10)

,Fields,Description
0,bearer id,xDr session identifier
1,Dur. (ms),Total Duration of the xDR (in ms)
2,Start,Start time of the xDR (first frame timestamp)
3,Start ms,Milliseconds offset of start time for the xDR (first frame timestamp)
4,End,End time of the xDR (last frame timestamp)
5,End ms,Milliseconds offset of end time of the xDR (last frame timestamp)
6,Dur. (s),Total Duration of the xDR (in s)
7,IMSI,International Mobile Subscriber Identity
8,MSISDN/Number,MS International PSTN/ISDN Number of mobile - customer number
9,IMEI,International Mobile Equipment Identity

In [391]:
# 11. Set a large value for the maximum column width
pd.set_option('display.max_colwidth', 100)

In [392]:
# 12. Data Sample
data_dictionary.head(60)

,Fields,Description
0,bearer id,xDr session identifier
1,Dur. (ms),Total Duration of the xDR (in ms)
2,Start,Start time of the xDR (first frame timestamp)
3,Start ms,Milliseconds offset of start time for the xDR (first frame timestamp)
4,End,End time of the xDR (last frame timestamp)
5,End ms,Milliseconds offset of end time of the xDR (last frame timestamp)
6,Dur. (s),Total Duration of the xDR (in s)
7,IMSI,International Mobile Subscriber Identity
8,MSISDN/Number,MS International PSTN/ISDN Number of mobile - customer number
9,IMEI,International Mobile Equipment Identity
10,Last Location Name,User location call name (2G/3G/4G) at the end of the bearer
11,Avg RTT DL (ms),Average Round Trip Time measurement Downlink direction (msecond)
12,Avg RTT UL (ms),Average Round Trip Time measurement Uplink direction (msecond)
13,Avg Bearer TP DL (kbps),Average Bearer Throughput for Downlink (kbps) - based on BDR duration
14,Avg Bearer TP UL (kbps),Average Bearer Throughput for uplink (kbps) - based on BDR duration
15,TCP DL Retrans. Vol (Bytes),TCP volume of Downlink packets detected as retransmitted (bytes)
16,TCP UL Retrans. Vol (Bytes),TCP volume of Uplink packets detected as retransmitted (bytes)
17,DL TP < 50 Kbps (%),Duration ratio when Bearer Downlink Throughput < ….
18,50 Kbps < DL TP < 250 Kbps (%),Duration ratio when Bearer Downlink Throughput range is …
19,250 Kbps < DL TP < 1 Mbps (%),Duration ratio when Bearer Downlink Throughput range is …
20,DL TP > 1 Mbps (%),Duration ratio when Bearer Downlink Throughput > ….
21,UL TP < 10 Kbps (%),Duration ratio when Bearer Uplink Throughput < ….
22,10 Kbps < UL TP < 50 Kbps (%),Duration ratio when Bearer Uplink Throughput range is …
23,50 Kbps < UL TP < 300 Kbps (%),Duration ratio when Bearer Uplink Throughput range is …
24,UL TP > 300 Kbps (%),Duration ratio when Bearer Uplink Throughput > ….
25,HTTP DL (Bytes),HTTP data volume (in Bytes) received by the MS during this session
26,HTTP UL (Bytes),HTTP data volume (in Bytes) sent by the MS during this session
27,Activity Duration DL (ms),Activity Duration for downlink (ms) - excluding periods of inactivity > 500 ms
28,Activity Duration UL (ms),Activity Duration for uplink (ms) - excluding periods of inactivity > 500 ms
29,Dur. (ms).1,Total Duration of the xDR (in ms)
30,Handset Manufacturer,Handset manufacturer
31,Handset Type,Handset type of the mobile device
32,Nb of sec with 125000B < Vol DL,Number of seconds with IP Volume DL >
33,Nb of sec with 1250B < Vol UL < 6250B,Number of seconds with IP Volume UL between …
34,Nb of sec with 31250B < Vol DL < 125000B,Number of seconds with IP Volume DL between …
35,Nb of sec with 37500B < Vol UL,Number of seconds with IP Volume UL >
36,Nb of sec with 6250B < Vol DL < 31250B,Number of seconds with IP Volume DL between …
37,Nb of sec with 6250B < Vol UL < 37500B,Number of seconds with IP Volume UL between …
38,Nb of sec with Vol DL < 6250B,Number of seconds with IP Volume DL <
39,Nb of sec with Vol UL < 1250B,Number of seconds with IP Volume UL <
40,Social Media DL (Bytes),Social Media data volume (in Bytes) received by the MS during this session
41,Social Media UL (Bytes),Social Media data volume (in Bytes) sent by the MS during this session
42,YouTube DL (Bytes),YouTube data volume (in Bytes) received by the MS during this session
43,YouTube UL (Bytes),YouTube data volume (in Bytes) sent by the MS during this session
44,Netflix DL (Bytes),Netflix data volume (in Bytes) received by the MS during this session
45,Netflix UL (Bytes),Netflix data volume (in Bytes) sent by the MS during this session
46,Google DL (Bytes),Google data volume (in Bytes) Received by the MS during this session
47,Google UL (Bytes),Google data volume (in Bytes) sent by the MS during this session
48,Email DL (Bytes),Email data volume (in Bytes) Received by the MS during this session
49,Email UL (Bytes),Email data volume (in Bytes) sent by the MS during this session
50,Gaming DL (Bytes),Gaming data volume (in Bytes) Received by the MS during this session
51,Gaming UL (Bytes),Gaming data volume (in Bytes) sent by the MS during this session
52,Other DL,Other data volume (in Bytes) received by the MS during this session
53,Other UL,Other data volume (in Bytes) sent by the MS during this session
54,Total DL (Bytes),Data volume (in Bytes) received by the MS during this session (IP layer + overhead)
55,Total UL (Bytes),Data volume (in Bytes) sent by the MS during this session (IP layer + overhead)

## **Exploratory Analysis**

In [393]:
# 13. Info
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      140442 non-null  object
 30  Handset Type                              140442 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [394]:
# 14. Descriptive Statistics
dataset.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000.000000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,122172.000000,122189.000000,150000.000000,150000.000000,6.185500e+04,5.335200e+04,149247.000000,149247.000000,149247.000000,149247.000000,149209.000000,149209.000000,149209.000000,149209.000000,6.852700e+04,6.819100e+04,1.500000e+05,1.500000e+05,1.500000e+05,52463.000000,57107.000000,56415.000000,19747.000000,61684.000000,38158.000000,149246.000000,149208.000000,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,109.795706,17.662883,13300.045927,1770.428647,2.080991e+07,7.596587e+05,92.844754,3.069355,1.717341,1.609654,98.530142,0.776749,0.147987,0.078923,1.144710e+08,3.242301e+06,1.829177e+06,1.408880e+06,1.046091e+08,989.699998,340.434395,810.837401,149.257052,965.464756,141.304812,3719.787552,4022.083454,1.795322e+06,32928.434380,5.750753e+06,2.056542e+06,1.791729e+06,467373.441940,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893173e+18,288.611834,288.097653,8.103762e+04,2.148809e+10,2.447443e+12,2.241637e+13,619.782739,84.793524,23971.878541,4625.355500,1.825665e+08,2.645305e+07,13.038031,6.215233,4.159538,4.828890,4.634285,3.225176,1.624523,1.295396,9.631946e+08,1.957064e+07,5.696395e+06,4.643231e+06,8.103761e+07,2546.524440,1445.365032,1842.162008,1219.112287,1946.387608,993.349688,9171.609010,10160.324314,1.035482e+06,19006.178256,3.309097e+06,1.189917e+06,1.035840e+06,269969.307031,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,0.000000,2.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000e+01,4.000000e+01,0.000000e+00,0.000000e+00,7.142988e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.200000e+01,0.000000,2.070000e+02,3.000000e+00,1.400000e+01,2.000000,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.744050e+04,2.082014e+14,3.365130e+10,3.546071e+13,32.000000,2.000000,43.000000,47.000000,3.565150e+04,4.694750e+03,91.000000,0.000000,0.000000,0.000000,99.000000,0.000000,0.000000,0.000000,1.124035e+05,2.432200e+04,1.487775e+04,2.153975e+04,5.744079e+07,20.000000,10.000000,26.000000,2.000000,39.000000,3.000000,87.000000,106.000000,8.991480e+05,16448.000000,2.882393e+06,1.024279e+06,8.927930e+05,233383.000000,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572201e+13,45.000000,5.000000,63.000000,63.000000,5.687300e+05,2.094950e+04,100.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,1.941949e+06,2.297330e+05,3.930450e+04,4.679350e+04,8.639998e+07,128.000000,52.000000,164.000000,8.000000,288.000000,8.000000,203.000000,217.000000,1.794369e+06,32920.000000,5.765829e+06,2.054573e+06,1.793505e+06,466250.000000,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304243e+19,749.000000,750.000000,1.324302e+05,2.082018e+14,3.368349e+10,8.611970e+13,70.000000,15.000000,19710.750000,1120.000000,3.768308e+06,8.402025e+04,100.000000,4.000000,1.000000,0.000000,100.000000,0.000000,0.000000,0.000000,2.504290e+07,1.542827e+06,6.796095e+05,5.990952e+05,1.324308e+08,693.500000,203.000000,757.000000,35.000000,1092.000000,31.000000,2650.000000,2451.000000,2.694938e+06,49334.000000,8.623552e+06,3.088454e+06,2.689327e+06,700440.000000,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,58613.000000,4.294426e+09,2.908226e+09,100.000000,93.000000,100.000000,94.000000,100.000000,98.000000,100.000000,96.000000,7.253064e+10,1.491890e+09,1.365365e+08,1.449113e+08,1.859336e+09,81476.000000,85412.000000,58525.000000,50553.000000,66913.000000,49565.000000,604061.000000,604122.000000,3.586064e+06,65870.000000,1.146283e+07,4.121357e+06,3.586146e+06,936418.000000,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

It doesn’t make sense to calculate descriptive statistics for Beared Id, IMSI, MSISDN / Number, and IMEI. However, the describe() method calculates statistics for all numerical columns. These statistics are being calculated before the data is cleaned. Therefore, there may be changes after missing values and outliers are handled.

In [395]:
# 15. Shape
dataset.shape

(150001, 55)

In [396]:
# 16. Shape
data_dictionary.shape

(56, 2)

There are 150,001 rows and 55 columns in the dataframe. However, we have 56 columns with their names and descriptions in the dictionary. This means there is a column described but not included in the dataframe. Let’s identify the missing column.

In [397]:
# 17. Concatenate the dataframes
df_compare_columns = pd.concat([pd.Series(dataset.columns.tolist()), data_dictionary['Fields']],
                               axis=1)

In [398]:
df_compare_columns

,0,Fields
0,Bearer Id,bearer id
1,Start,Dur. (ms)
2,Start ms,Start
3,End,Start ms
4,End ms,End
5,Dur. (ms),End ms
6,IMSI,Dur. (s)
7,MSISDN/Number,IMSI
8,IMEI,MSISDN/Number
9,Last Location Name,IMEI
10,Avg RTT DL (ms),Last Location Name
11,Avg RTT UL (ms),Avg RTT DL (ms)
12,Avg Bearer TP DL (kbps),Avg RTT UL (ms)
13,Avg Bearer TP UL (kbps),Avg Bearer TP DL (kbps)
14,TCP DL Retrans. Vol (Bytes),Avg Bearer TP UL (kbps)
15,TCP UL Retrans. Vol (Bytes),TCP DL Retrans. Vol (Bytes)
16,DL TP < 50 Kbps (%),TCP UL Retrans. Vol (Bytes)
17,50 Kbps < DL TP < 250 Kbps (%),DL TP < 50 Kbps (%)
18,250 Kbps < DL TP < 1 Mbps (%),50 Kbps < DL TP < 250 Kbps (%)
19,DL TP > 1 Mbps (%),250 Kbps < DL TP < 1 Mbps (%)
20,UL TP < 10 Kbps (%),DL TP > 1 Mbps (%)
21,10 Kbps < UL TP < 50 Kbps (%),UL TP < 10 Kbps (%)
22,50 Kbps < UL TP < 300 Kbps (%),10 Kbps < UL TP < 50 Kbps (%)
23,UL TP > 300 Kbps (%),50 Kbps < UL TP < 300 Kbps (%)
24,HTTP DL (Bytes),UL TP > 300 Kbps (%)
25,HTTP UL (Bytes),HTTP DL (Bytes)
26,Activity Duration DL (ms),HTTP UL (Bytes)
27,Activity Duration UL (ms),Activity Duration DL (ms)
28,Dur. (ms).1,Activity Duration UL (ms)
29,Handset Manufacturer,Dur. (ms).1
30,Handset Type,Handset Manufacturer
31,Nb of sec with 125000B < Vol DL,Handset Type
32,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 125000B < Vol DL
33,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 1250B < Vol UL < 6250B
34,Nb of sec with 37500B < Vol UL,Nb of sec with 31250B < Vol DL < 125000B
35,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 37500B < Vol UL
36,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with 6250B < Vol DL < 31250B
37,Nb of sec with Vol DL < 6250B,Nb of sec with 6250B < Vol UL < 37500B
38,Nb of sec with Vol UL < 1250B,Nb of sec with Vol DL < 6250B
39,Social Media DL (Bytes),Nb of sec with Vol UL < 1250B
40,Social Media UL (Bytes),Social Media DL (Bytes)
41,Google DL (Bytes),Social Media UL (Bytes)
42,Google UL (Bytes),YouTube DL (Bytes)
43,Email DL (Bytes),YouTube UL (Bytes)
44,Email UL (Bytes),Netflix DL (Bytes)
45,Youtube DL (Bytes),Netflix UL (Bytes)
46,Youtube UL (Bytes),Google DL (Bytes)
47,Netflix DL (Bytes),Google UL (Bytes)
48,Netflix UL (Bytes),Email DL (Bytes)
49,Gaming DL (Bytes),Email UL (Bytes)
50,Gaming UL (Bytes),Gaming DL (Bytes)
51,Other DL (Bytes),Gaming UL (Bytes)
52,Other UL (Bytes),Other DL
53,Total UL (Bytes),Other UL
54,Total DL (Bytes),Total DL (Bytes)
55,NaN,Total UL (Bytes)

In [399]:
# 18. Rename the columns
df_compare_columns.rename(columns={0: 'Column in Dataset', 'Fields': 'Column in Dictionary'},
                          inplace=True)

In [400]:
# 19. View
df_compare_columns

,Column in Dataset,Column in Dictionary
0,Bearer Id,bearer id
1,Start,Dur. (ms)
2,Start ms,Start
3,End,Start ms
4,End ms,End
5,Dur. (ms),End ms
6,IMSI,Dur. (s)
7,MSISDN/Number,IMSI
8,IMEI,MSISDN/Number
9,Last Location Name,IMEI
10,Avg RTT DL (ms),Last Location Name
11,Avg RTT UL (ms),Avg RTT DL (ms)
12,Avg Bearer TP DL (kbps),Avg RTT UL (ms)
13,Avg Bearer TP UL (kbps),Avg Bearer TP DL (kbps)
14,TCP DL Retrans. Vol (Bytes),Avg Bearer TP UL (kbps)
15,TCP UL Retrans. Vol (Bytes),TCP DL Retrans. Vol (Bytes)
16,DL TP < 50 Kbps (%),TCP UL Retrans. Vol (Bytes)
17,50 Kbps < DL TP < 250 Kbps (%),DL TP < 50 Kbps (%)
18,250 Kbps < DL TP < 1 Mbps (%),50 Kbps < DL TP < 250 Kbps (%)
19,DL TP > 1 Mbps (%),250 Kbps < DL TP < 1 Mbps (%)
20,UL TP < 10 Kbps (%),DL TP > 1 Mbps (%)
21,10 Kbps < UL TP < 50 Kbps (%),UL TP < 10 Kbps (%)
22,50 Kbps < UL TP < 300 Kbps (%),10 Kbps < UL TP < 50 Kbps (%)
23,UL TP > 300 Kbps (%),50 Kbps < UL TP < 300 Kbps (%)
24,HTTP DL (Bytes),UL TP > 300 Kbps (%)
25,HTTP UL (Bytes),HTTP DL (Bytes)
26,Activity Duration DL (ms),HTTP UL (Bytes)
27,Activity Duration UL (ms),Activity Duration DL (ms)
28,Dur. (ms).1,Activity Duration UL (ms)
29,Handset Manufacturer,Dur. (ms).1
30,Handset Type,Handset Manufacturer
31,Nb of sec with 125000B < Vol DL,Handset Type
32,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 125000B < Vol DL
33,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 1250B < Vol UL < 6250B
34,Nb of sec with 37500B < Vol UL,Nb of sec with 31250B < Vol DL < 125000B
35,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 37500B < Vol UL
36,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with 6250B < Vol DL < 31250B
37,Nb of sec with Vol DL < 6250B,Nb of sec with 6250B < Vol UL < 37500B
38,Nb of sec with Vol UL < 1250B,Nb of sec with Vol DL < 6250B
39,Social Media DL (Bytes),Nb of sec with Vol UL < 1250B
40,Social Media UL (Bytes),Social Media DL (Bytes)
41,Google DL (Bytes),Social Media UL (Bytes)
42,Google UL (Bytes),YouTube DL (Bytes)
43,Email DL (Bytes),YouTube UL (Bytes)
44,Email UL (Bytes),Netflix DL (Bytes)
45,Youtube DL (Bytes),Netflix UL (Bytes)
46,Youtube UL (Bytes),Google DL (Bytes)
47,Netflix DL (Bytes),Google UL (Bytes)
48,Netflix UL (Bytes),Email DL (Bytes)
49,Gaming DL (Bytes),Email UL (Bytes)
50,Gaming UL (Bytes),Gaming DL (Bytes)
51,Other DL (Bytes),Gaming UL (Bytes)
52,Other UL (Bytes),Other DL
53,Total UL (Bytes),Other UL
54,Total DL (Bytes),Total DL (Bytes)
55,NaN,Total UL (Bytes)

“Dur. (Ms)” is ignored in the dataset as seen at index 1 in df_compare_columns. This is where the column order started to shift.

However, the same column name “Dur. (Ms)” appears in the dataset at index 5, while the dictionary file lists it as “Dur. (S)” at index 6. Since the measurements of both columns differ as indicated in their names, we need to verify which one is correct. To investigate this, we will use the column “Dur. (Ms) .1” found at indices 28 and 29 in both the dataset and the dictionary file.

In [401]:
# 20. Inspect the columns 'Dur. (ms)' and 'Dur. (ms).1'
dataset[['Dur. (ms)', 'Dur. (ms).1']]

        Dur. (ms)   Dur. (ms).1
0       1823652.0  1.823653e+09
1       1365104.0  1.365104e+09
2       1361762.0  1.361763e+09
3       1321509.0  1.321510e+09
4       1089009.0  1.089009e+09
...           ...           ...
149996    81230.0  8.123076e+07
149997    97970.0  9.797070e+07
149998    98249.0  9.824953e+07
149999    97910.0  9.791063e+07
150000        NaN           NaN

[150001 rows x 2 columns]

It seems that the column “Dur. (Ms)” is measured in seconds. Therefore, we will rename it appropriately. We will also rename some of the columns to clarify their meaning and to match the naming style of the other columns.

In [402]:
# 21. Rename columns
dataset.rename(columns={'Dur. (ms)': 'Dur (s)',
                        'Dur. (ms).1': 'Dur (ms)',
                        'Start ms': 'Start Offset (ms)',
                        'End ms': 'End Offset (ms)'},
               inplace=True)

In [403]:
# 22. List of dataset columns
dataset.columns.tolist()

['Bearer Id',
 'Start',
 'Start Offset (ms)',
 'End',
 'End Offset (ms)',
 'Dur (s)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur (ms)',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

In [404]:
# 23. Shape
dataset.shape

(150001, 55)

## **24. Step 1 - Handling Missing Values**

### 1 - Identifying Missing Values
### 2 - Dropping Columns
### 3 - Backward Fill Imputation
### 4 - Forward Fill Imputation
### 5 - Imputation of Categorical Variables
### 6 - Dropping Rows

### **1.1. Identifying Missing Values**

In [405]:
# 24. Function to calculate the percentage of missing values
def calculate_missing_values_percentage(df):

    # Calculate the total number of cells in the dataset
    total_cells = np.product(df.shape)

    # Count the number of missing values per column
    missing_count = df.isnull().sum()

    # Calculate the total number of missing values
    total_missing = missing_count.sum()

    # Calculate the percentage of missing values
    print("The dataset has", round(((total_missing / total_cells) * 100), 2), "%", "of missing values.")

In [406]:
# 25. Check the percentage of missing values
calculate_missing_values_percentage(dataset)

The dataset has 12.72 % of missing values.

In [407]:
# 26. Function to calculate missing values by column
def calculate_missing_values_by_column(df):

    # Total missing values
    missing_values = df.isnull().sum()

    # Percentage of missing values
    missing_values_percent = 100 * missing_values / len(df)

    # Data type of columns with missing values
    missing_values_dtype = df.dtypes

    # Create a table with the results
    missing_values_table = pd.concat([missing_values, missing_values_percent, missing_values_dtype], axis=1)

    # Rename the columns
    missing_values_table_renamed = missing_values_table.rename(
        columns={0: 'Missing Values', 1: '% of Missing Values', 2: 'Dtype'})

    # Sort the table by percentage of missing values in descending order and remove columns with no missing values
    missing_values_table_renamed = missing_values_table_renamed[missing_values_table_renamed.iloc[:, 0] != 0] \
                                   .sort_values('% of Missing Values', ascending=False).round(2)

    # Print information
    print("The dataset has " + str(df.shape[1]) + " columns.\n"
          "Found: " + str(missing_values_table_renamed.shape[0]) + " columns with missing values.")

    if missing_values_table_renamed.shape[0] == 0:
        return

    # Return the dataframe with missing value information
    return missing_values_table_renamed

In [408]:
# 27. Create table with missing values
df_missing = calculate_missing_values_by_column(dataset)

The dataset has 55 columns.
Found: 41 columns with missing values.

In [409]:
# 28. View
df_missing

,Missing Values,% of Missing Values,Dtype
Nb of sec with 37500B < Vol UL,130254,86.84,float64
Nb of sec with 6250B < Vol UL < 37500B,111843,74.56,float64
Nb of sec with 125000B < Vol DL,97538,65.02,float64
TCP UL Retrans. Vol (Bytes),96649,64.43,float64
Nb of sec with 31250B < Vol DL < 125000B,93586,62.39,float64
Nb of sec with 1250B < Vol UL < 6250B,92894,61.93,float64
Nb of sec with 6250B < Vol DL < 31250B,88317,58.88,float64
TCP DL Retrans. Vol (Bytes),88146,58.76,float64
HTTP UL (Bytes),81810,54.54,float64
HTTP DL (Bytes),81474,54.32,float64
Avg RTT DL (ms),27829,18.55,float64
Avg RTT UL (ms),27812,18.54,float64
Handset Manufacturer,9559,6.37,object
Handset Type,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
Start,1,0.00,object
End Offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Start Offset (ms),1,0.00,float64
End,1,0.00,object
Avg Bearer TP DL (kbps),1,0.00,float64
Dur (s),1,0.00,float64
Avg Bearer TP UL (kbps),1,0.00,float64
Dur (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Total DL (Bytes),1,0.00,float64

Generally, columns with more than 50% missing values should be removed. Between 30% and 50% is optional.

But the final decision is always yours! Yes, you, Data Analyst. Just remember to always justify your decisions.

In this project, we will remove columns where missing values represent more than 30% of the variable, as we have a large number of columns with missing values and, consequently, a lot of work. We will handle variables with a low percentage of missing values and delete those with a high percentage of missing values.


### **1.2. Dropping Columns**

In [410]:
# 29. Columns to be removed
columns_to_remove = df_missing[df_missing['% of Missing Values'] >= 30.00].index.tolist()

In [411]:
# 30. Columns to be removed
columns_to_remove

['Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with 125000B < Vol DL',
 'TCP UL Retrans. Vol (Bytes)',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'TCP DL Retrans. Vol (Bytes)',
 'HTTP UL (Bytes)',
 'HTTP DL (Bytes)']

Even though the “TCP” variables have many missing values, instead of removing them, we will apply imputation to these variables, as they may be necessary for our later analysis.

In [412]:
# 31. Columns to be removed
columns_to_remove = [col for col in columns_to_remove if col not in ['TCP UL Retrans. Vol (Bytes)',
                                                                     'TCP DL Retrans. Vol (Bytes)']]

In [413]:
# 32. Columns to be removed
columns_to_remove

['Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'HTTP UL (Bytes)',
 'HTTP DL (Bytes)']

In [414]:
# 33. Drop the columns and create another dataframe
cleaned_dataset = dataset.drop(columns_to_remove, axis=1)

In [415]:
# 34. Shape
cleaned_dataset.shape

(150001, 47)

Now let’s check the status of missing values in the modified dataframe.

In [416]:
# 35. Check the percentage of missing values in the cleaned dataframe
calculate_missing_values_percentage(cleaned_dataset)

The dataset has 3.85 % of missing values.

In [417]:
# 36. Check missing values by column in the cleaned dataframe
calculate_missing_values_by_column(cleaned_dataset)

The dataset has 47 columns.
Found: 33 columns with missing values.

                                Missing Values  % of Missing Values    Dtype
TCP UL Retrans. Vol (Bytes)              96649                64.43  float64
TCP DL Retrans. Vol (Bytes)              88146                58.76  float64
Avg RTT DL (ms)                          27829                18.55  float64
Avg RTT UL (ms)                          27812                18.54  float64
Handset Type                              9559                 6.37   object
Handset Manufacturer                      9559                 6.37   object
Last Location Name                        1153                 0.77   object
MSISDN/Number                             1066                 0.71  float64
Bearer Id                                  991                 0.66  float64
Nb of sec with Vol UL < 1250B              793                 0.53  float64
10 Kbps < UL TP < 50 Kbps (%)              792                 0.53  float64
UL TP < 10 Kbps (%)                        792                 0.53  float64
50 Kbps < UL TP < 300 Kbps (%)             792                 0.53  float64
UL TP > 300 Kbps (%)                       792                 0.53  float64
Nb of sec with Vol DL < 6250B              755                 0.50  float64
250 Kbps < DL TP < 1 Mbps (%)              754                 0.50  float64
DL TP > 1 Mbps (%)                         754                 0.50  float64
DL TP < 50 Kbps (%)                        754                 0.50  float64
50 Kbps < DL TP < 250 Kbps (%)             754                 0.50  float64
IMEI                                       572                 0.38  float64
IMSI                                       570                 0.38  float64
Start                                        1                 0.00   object
Avg Bearer TP UL (kbps)                      1                 0.00  float64
Avg Bearer TP DL (kbps)                      1                 0.00  float64
Activity Duration DL (ms)                    1                 0.00  float64
Activity Duration UL (ms)                    1                 0.00  float64
Dur (ms)                                     1                 0.00  float64
Dur (s)                                      1                 0.00  float64
End Offset (ms)                              1                 0.00  float64
End                                          1                 0.00   object
Start Offset (ms)                            1                 0.00  float64
Total UL (Bytes)                             1                 0.00  float64
Total DL (Bytes)                             1                 0.00  float64

### **1.3. Backward Fill Imputation**

Since the percentages of missing values for ‘TCP UL Retrans. Vol (Bytes)’ and ‘TCP DL Retrans. Vol (Bytes)’ are very high, we will apply backward fill imputation for the missing values.

In this case, using a single value like the mean or median is not advisable, as it may alter our data in an undesirable way, making most values equal to a single value.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html

In [418]:
# 37. Backward fill imputation for missing values
# method='bfill': Bfill or backward-fill propagates the first non-null observed value backwards
# until another non-null value is encountered.
def backward_fill_missing_values(df, col):

    count = df[col].isna().sum()

    df[col] = df[col].fillna(method='bfill')

    print(f"{count} missing values in column {col} were replaced using the backward fill method.")

In [419]:
# 38. Backward fill imputation on the 'TCP UL Retrans. Vol (Bytes)' variable
backward_fill_missing_values(cleaned_dataset, 'TCP UL Retrans. Vol (Bytes)')

96649 missing values in column TCP UL Retrans. Vol (Bytes) were replaced using the backward fill method.

In [420]:
# 39. Backward fill imputation on the 'TCP DL Retrans. Vol (Bytes)' variable
backward_fill_missing_values(cleaned_dataset, 'TCP DL Retrans. Vol (Bytes)')

88146 missing values in column TCP DL Retrans. Vol (Bytes) were replaced using the backward fill method.

### **1.4. Forward Fill Imputation**

In [421]:
# 40. Check missing values by column in the cleaned dataframe
calculate_missing_values_by_column(cleaned_dataset)

The dataset has 47 columns.
Found: 33 columns with missing values.

                                Missing Values  % of Missing Values    Dtype
Avg RTT DL (ms)                          27829                18.55  float64
Avg RTT UL (ms)                          27812                18.54  float64
Handset Type                              9559                 6.37   object
Handset Manufacturer                      9559                 6.37   object
Last Location Name                        1153                 0.77   object
MSISDN/Number                             1066                 0.71  float64
Bearer Id                                  991                 0.66  float64
Nb of sec with Vol UL < 1250B              793                 0.53  float64
UL TP > 300 Kbps (%)                       792                 0.53  float64
50 Kbps < UL TP < 300 Kbps (%)             792                 0.53  float64
10 Kbps < UL TP < 50 Kbps (%)              792                 0.53  float64
UL TP < 10 Kbps (%)                        792                 0.53  float64
Nb of sec with Vol DL < 6250B              755                 0.50  float64
50 Kbps < DL TP < 250 Kbps (%)             754                 0.50  float64
DL TP > 1 Mbps (%)                         754                 0.50  float64
250 Kbps < DL TP < 1 Mbps (%)              754                 0.50  float64
DL TP < 50 Kbps (%)                        754                 0.50  float64
IMEI                                       572                 0.38  float64
IMSI                                       570                 0.38  float64
TCP UL Retrans. Vol (Bytes)                  5                 0.00  float64
TCP DL Retrans. Vol (Bytes)                  5                 0.00  float64
Start                                        1                 0.00   object
Avg Bearer TP UL (kbps)                      1                 0.00  float64
Avg Bearer TP DL (kbps)                      1                 0.00  float64
Activity Duration DL (ms)                    1                 0.00  float64
Activity Duration UL (ms)                    1                 0.00  float64
Dur (ms)                                     1                 0.00  float64
Dur (s)                                      1                 0.00  float64
End Offset (ms)                              1                 0.00  float64
End                                          1                 0.00   object
Start Offset (ms)                            1                 0.00  float64
Total UL (Bytes)                             1                 0.00  float64
Total DL (Bytes)                             1                 0.00  float64

The variables “Avg RTT DL (ms)” and “Avg RTT UL (ms)” have the next highest percentages of missing values, with approximately 18.5% each. Let’s check if these variables are skewed (do not follow a normal distribution) using the skew() method, which returns the skewness coefficient.

In [422]:
# 41. Check skewness for 'Avg RTT DL (ms)'
cleaned_dataset['Avg RTT DL (ms)'].skew(skipna=True)

62.90782807995961

In [423]:
# 42. Check skewness for 'Avg RTT UL (ms)'
cleaned_dataset['Avg RTT UL (ms)'].skew(skipna=True)

28.45741458546382

	•	If skewness is between -0.5 and 0.5, the data is fairly symmetrical.
	•	If skewness is between -1 and -0.5 or between 0.5 and 1, the data is moderately skewed.
	•	If skewness is less than -1 or greater than 1, the data is highly skewed.

Since both columns, “Avg RTT DL (ms)” and “Avg RTT UL (ms),” are highly positively skewed, it is advisable not to impute them with their mean. Therefore, we will use forward fill imputation.

In [424]:
# 43. Forward fill imputation for missing values
# method='ffill': Ffill or forward-fill propagates the last non-null observed value forward
# until another non-null value is encountered.
def forward_fill_missing_values(df, col):

    count = df[col].isna().sum()

    df[col] = df[col].fillna(method='ffill')

    print(f"{count} missing values in column {col} were replaced using the forward fill method.")

In [425]:
# 44. Forward fill imputation on 'Avg RTT DL (ms)'
forward_fill_missing_values(cleaned_dataset, 'Avg RTT DL (ms)')

27829 missing values in column Avg RTT DL (ms) were replaced using the forward fill method.

In [426]:
# 45. Forward fill imputation on 'Avg RTT UL (ms)'
forward_fill_missing_values(cleaned_dataset, 'Avg RTT UL (ms)')

27812 missing values in column Avg RTT UL (ms) were replaced using the forward fill method.

We check for missing values again.

In [427]:
# 46. Check the percentage of missing values in the cleaned dataframe
calculate_missing_values_percentage(cleaned_dataset)

The dataset has 0.44 % of missing values.

In [428]:
# 47. Check missing values by column in the cleaned dataframe
calculate_missing_values_by_column(cleaned_dataset)

The dataset has 47 columns.
Found: 31 columns with missing values.

                                Missing Values  % of Missing Values    Dtype
Handset Type                              9559                 6.37   object
Handset Manufacturer                      9559                 6.37   object
Last Location Name                        1153                 0.77   object
MSISDN/Number                             1066                 0.71  float64
Bearer Id                                  991                 0.66  float64
Nb of sec with Vol UL < 1250B              793                 0.53  float64
UL TP > 300 Kbps (%)                       792                 0.53  float64
50 Kbps < UL TP < 300 Kbps (%)             792                 0.53  float64
10 Kbps < UL TP < 50 Kbps (%)              792                 0.53  float64
UL TP < 10 Kbps (%)                        792                 0.53  float64
Nb of sec with Vol DL < 6250B              755                 0.50  float64
DL TP < 50 Kbps (%)                        754                 0.50  float64
DL TP > 1 Mbps (%)                         754                 0.50  float64
250 Kbps < DL TP < 1 Mbps (%)              754                 0.50  float64
50 Kbps < DL TP < 250 Kbps (%)             754                 0.50  float64
IMEI                                       572                 0.38  float64
IMSI                                       570                 0.38  float64
TCP UL Retrans. Vol (Bytes)                  5                 0.00  float64
TCP DL Retrans. Vol (Bytes)                  5                 0.00  float64
Start                                        1                 0.00   object
Avg Bearer TP UL (kbps)                      1                 0.00  float64
Avg Bearer TP DL (kbps)                      1                 0.00  float64
Activity Duration DL (ms)                    1                 0.00  float64
Activity Duration UL (ms)                    1                 0.00  float64
Dur (ms)                                     1                 0.00  float64
Dur (s)                                      1                 0.00  float64
End Offset (ms)                              1                 0.00  float64
End                                          1                 0.00   object
Start Offset (ms)                            1                 0.00  float64
Total UL (Bytes)                             1                 0.00  float64
Total DL (Bytes)                             1                 0.00  float64

### **1.5. Imputation of Categorical Variables**

In [429]:
# 48. Information about the cleaned dataframe
cleaned_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 47 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Bearer Id                       149010 non-null  float64
 1   Start                           150000 non-null  object
 2   Start Offset (ms)               150000 non-null  float64
 3   End                             150000 non-null  object
 4   End Offset (ms)                 150000 non-null  float64
 5   Dur (s)                         150000 non-null  float64
 6   IMSI                            149431 non-null  float64
 7   MSISDN/Number                   148935 non-null  float64
 8   IMEI                            149429 non-null  float64
 9   Last Location Name              148848 non-null  object
 10  Avg RTT DL (ms)                 150001 non-null  float64
 11  Avg RTT UL (ms)                 150001 non-null  float64
 12  Avg Bearer TP DL (kbps)         150000 non-null  float64
 13  Avg Bearer TP UL (kbps)         150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)     149996 non-null  float64
 15  TCP UL Retrans. Vol (Bytes)     149996 non-null  float64
 16  DL TP < 50 Kbps (%)             149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)  149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)   149247 non-null  float64
 19  DL TP > 1 Mbps (%)              149247 non-null  float64
 20  UL TP < 10 Kbps (%)             149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)   149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)  149209 non-null  float64
 23  UL TP > 300 Kbps (%)            149209 non-null  float64
 24  Activity Duration DL (ms)       150000 non-null  float64
 25  Activity Duration UL (ms)       150000 non-null  float64
 26  Dur (ms)                        150000 non-null  float64
 27  Handset Manufacturer            140442 non-null  object
 28  Handset Type                    140442 non-null  object
 29  Nb of sec with Vol DL < 6250B   149246 non-null  float64
 30  Nb of sec with Vol UL < 1250B   149208 non-null  float64
 31  Social Media DL (Bytes)         150001 non-null  float64
 32  Social Media UL (Bytes)         150001 non-null  float64
 33  Google DL (Bytes)               150001 non-null  float64
 34  Google UL (Bytes)               150001 non-null  float64
 35  Email DL (Bytes)                150001 non-null  float64
 36  Email UL (Bytes)                150001 non-null  float64
 37  Youtube DL (Bytes)              150001 non-null  float64
 38  Youtube UL (Bytes)              150001 non-null  float64
 39  Netflix DL (Bytes)              150001 non-null  float64
 40  Netflix UL (Bytes)              150001 non-null  float64
 41  Gaming DL (Bytes)               150001 non-null  float64
 42  Gaming UL (Bytes)               150001 non-null  float64
 43  Other DL (Bytes)                150001 non-null  float64
 44  Other UL (Bytes)                150001 non-null  float64
 45  Total UL (Bytes)                150000 non-null  float64
 46  Total DL (Bytes)                150000 non-null  float64
dtypes: float64(42), object(5)
memory usage: 53.8+ MB

Since “Handset Type” and “Handset Manufacturer” are categorical columns, it is best to impute them with the value “unknown” so as not to bias the data.

In [430]:
# 49. Fill missing values
def fill_missing_value(df, col, value):

    count = df[col].isna().sum()

    df[col] = df[col].fillna(value)

    if isinstance(value, str):
        print(f"{count} missing values in column {col} were replaced with '{value}'.")
    else:
        print(f"{count} missing values in column {col} were replaced with {value}.")

In [431]:
# 50. Impute categorical variables
fill_missing_value(cleaned_dataset, 'Handset Type', 'unknown')
fill_missing_value(cleaned_dataset, 'Handset Manufacturer', 'unknown')

9559 missing values in column Handset Type were replaced with 'unknown'.
9559 missing values in column Handset Manufacturer were replaced with 'unknown'.

> We check for missing values again.

In [432]:
# 51. Check the percentage of missing values in the cleaned dataframe
calculate_missing_values_percentage(cleaned_dataset)

The dataset has 0.17 % of missing values.

In [433]:
# 52. Check missing values by column in the cleaned dataframe
calculate_missing_values_by_column(cleaned_dataset)

The dataset has 47 columns.
Found: 29 columns with missing values.

                                Missing Values  % of Missing Values    Dtype
Last Location Name                        1153                 0.77   object
MSISDN/Number                             1066                 0.71  float64
Bearer Id                                  991                 0.66  float64
Nb of sec with Vol UL < 1250B              793                 0.53  float64
UL TP > 300 Kbps (%)                       792                 0.53  float64
50 Kbps < UL TP < 300 Kbps (%)             792                 0.53  float64
10 Kbps < UL TP < 50 Kbps (%)              792                 0.53  float64
UL TP < 10 Kbps (%)                        792                 0.53  float64
Nb of sec with Vol DL < 6250B              755                 0.50  float64
50 Kbps < DL TP < 250 Kbps (%)             754                 0.50  float64
DL TP > 1 Mbps (%)                         754                 0.50  float64
250 Kbps < DL TP < 1 Mbps (%)              754                 0.50  float64
DL TP < 50 Kbps (%)                        754                 0.50  float64
IMEI                                       572                 0.38  float64
IMSI                                       570                 0.38  float64
TCP UL Retrans. Vol (Bytes)                  5                 0.00  float64
TCP DL Retrans. Vol (Bytes)                  5                 0.00  float64
Start                                        1                 0.00   object
Avg Bearer TP UL (kbps)                      1                 0.00  float64
Avg Bearer TP DL (kbps)                      1                 0.00  float64
Dur (s)                                      1                 0.00  float64
End Offset (ms)                              1                 0.00  float64
Activity Duration DL (ms)                    1                 0.00  float64
Activity Duration UL (ms)                    1                 0.00  float64
Dur (ms)                                     1                 0.00  float64
End                                          1                 0.00   object
Start Offset (ms)                            1                 0.00  float64
Total UL (Bytes)                             1                 0.00  float64
Total DL (Bytes)                             1                 0.00  float64

### **1.6. Dropping Rows**

Since only 0.17% of the dataset contains missing values and the total number of rows is around 150,000, dropping these rows will not have a noticeable negative impact.

In [434]:
# 53. Drop rows with missing values
def drop_rows_with_na(df):

    old = df.shape[0]

    df.dropna(inplace=True)

    new = df.shape[0]

    count = old - new

    print(f"{count} rows containing missing values were dropped.")

In [435]:
# 54. Drop rows with missing values
drop_rows_with_na(cleaned_dataset)

3114 rows containing missing values were dropped.

In [436]:
# 55. Check the percentage of missing values in the cleaned dataframe
calculate_missing_values_percentage(cleaned_dataset)

The dataset has 0.0 % of missing values.

In [437]:
# 56. Shape
cleaned_dataset.shape

(146887, 47)

In [438]:
%watermark -a "panData"

Author: panData



---

## **Step 2 - Data Type Conversion**

In [439]:
# 57. Data types of each column in the cleaned dataframe
cleaned_dataset.dtypes

Bearer Id                         float64
Start                              object
Start Offset (ms)                 float64
End                                object
End Offset (ms)                   float64
Dur (s)                           float64
IMSI                              float64
MSISDN/Number                     float64
IMEI                              float64
Last Location Name                 object
Avg RTT DL (ms)                   float64
Avg RTT UL (ms)                   float64
Avg Bearer TP DL (kbps)           float64
Avg Bearer TP UL (kbps)           float64
TCP DL Retrans. Vol (Bytes)       float64
TCP UL Retrans. Vol (Bytes)       float64
DL TP < 50 Kbps (%)               float64
50 Kbps < DL TP < 250 Kbps (%)    float64
250 Kbps < DL TP < 1 Mbps (%)     float64
DL TP > 1 Mbps (%)                float64
UL TP < 10 Kbps (%)               float64
10 Kbps < UL TP < 50 Kbps (%)     float64
50 Kbps < UL TP < 300 Kbps (%)    float64
UL TP > 300 Kbps (%)              float64
Activity Duration DL (ms)         float64
Activity Duration UL (ms)         float64
Dur (ms)                          float64
Handset Manufacturer               object
Handset Type                       object
Nb of sec with Vol DL < 6250B     float64
Nb of sec with Vol UL < 1250B     float64
Social Media DL (Bytes)           float64
Social Media UL (Bytes)           float64
Google DL (Bytes)                 float64
Google UL (Bytes)                 float64
Email DL (Bytes)                  float64
Email UL (Bytes)                  float64
Youtube DL (Bytes)                float64
Youtube UL (Bytes)                float64
Netflix DL (Bytes)                float64
Netflix UL (Bytes)                float64
Gaming DL (Bytes)                 float64
Gaming UL (Bytes)                 float64
Other DL (Bytes)                  float64
Other UL (Bytes)                  float64
Total UL (Bytes)                  float64
Total DL (Bytes)                  float64
dtype: object

In [440]:
# 58. List of columns with data type 'object' in the cleaned dataframe
cleaned_dataset.select_dtypes(include='object').columns.tolist()

['Start', 'End', 'Last Location Name', 'Handset Manufacturer', 'Handset Type']

In [441]:
# 59. Display the first few rows of the cleaned dataframe
cleaned_dataset.head()

,Bearer Id,Start,Start Offset (ms),End,End Offset (ms),Dur (s),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Dur (ms),Handset Manufacturer,Handset Type,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,42.0,5.0,23.0,44.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,65.0,5.0,6.0,9.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,65.0,5.0,44.0,44.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,3330.0,37882.0,1.321510e+09,unknown,unknown,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,65.0,5.0,6.0,9.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

Looking at the columns, we can see that the “Start” and “End” columns are actually datetime values, even though they are labeled as objects by pandas. Besides these two columns, all other columns with object data types are actually string values. Therefore, we will convert these columns to their appropriate data types.

In [442]:
# 60. Function to convert columns to datetime
def convert_to_datetime(df, columns):
    for col in columns:
        df[col] = pd.to_datetime(df[col])

In [443]:
# 61. Convert columns to datetime
convert_to_datetime(cleaned_dataset, ['Start', 'End'])

In [444]:
# 62. Data types of each column in the cleaned dataframe
cleaned_dataset.dtypes

Bearer Id                                float64
Start                             datetime64[ns]
Start Offset (ms)                        float64
End                               datetime64[ns]
End Offset (ms)                          float64
Dur (s)                                  float64
IMSI                                     float64
MSISDN/Number                            float64
IMEI                                     float64
Last Location Name                        object
Avg RTT DL (ms)                          float64
Avg RTT UL (ms)                          float64
Avg Bearer TP DL (kbps)                  float64
Avg Bearer TP UL (kbps)                  float64
TCP DL Retrans. Vol (Bytes)              float64
TCP UL Retrans. Vol (Bytes)              float64
DL TP < 50 Kbps (%)                      float64
50 Kbps < DL TP < 250 Kbps (%)           float64
250 Kbps < DL TP < 1 Mbps (%)            float64
DL TP > 1 Mbps (%)                       float64
UL TP < 10 Kbps (%)                      float64
10 Kbps < UL TP < 50 Kbps (%)            float64
50 Kbps < UL TP < 300 Kbps (%)           float64
UL TP > 300 Kbps (%)                     float64
Activity Duration DL (ms)                float64
Activity Duration UL (ms)                float64
Dur (ms)                                 float64
Handset Manufacturer                      object
Handset Type                              object
Nb of sec with Vol DL < 6250B            float64
Nb of sec with Vol UL < 1250B            float64
Social Media DL (Bytes)                  float64
Social Media UL (Bytes)                  float64
Google DL (Bytes)                        float64
Google UL (Bytes)                        float64
Email DL (Bytes)                         float64
Email UL (Bytes)                         float64
Youtube DL (Bytes)                       float64
Youtube UL (Bytes)                       float64
Netflix DL (Bytes)                       float64
Netflix UL (Bytes)                       float64
Gaming DL (Bytes)                        float64
Gaming UL (Bytes)                        float64
Other DL (Bytes)                         float64
Other UL (Bytes)                         float64
Total UL (Bytes)                         float64
Total DL (Bytes)                         float64
dtype: object

In [445]:
# 63. Extract columns with data type 'object'
string_columns = cleaned_dataset.select_dtypes(include='object').columns.tolist()

In [446]:
# 64. View the list of columns with data type 'object'
string_columns

['Last Location Name', 'Handset Manufacturer', 'Handset Type']

In [447]:
# 65. Function to convert columns to string
def convert_to_string(df, columns):
    for col in columns:
        df[col] = df[col].astype("string")

In [448]:
# 66. Convert columns to string
convert_to_string(cleaned_dataset, string_columns)

In [449]:
# 67. Data types of each column in the cleaned dataframe
cleaned_dataset.dtypes

Bearer Id                                float64
Start                             datetime64[ns]
Start Offset (ms)                        float64
End                               datetime64[ns]
End Offset (ms)                          float64
Dur (s)                                  float64
IMSI                                     float64
MSISDN/Number                            float64
IMEI                                     float64
Last Location Name                string[python]
Avg RTT DL (ms)                          float64
Avg RTT UL (ms)                          float64
Avg Bearer TP DL (kbps)                  float64
Avg Bearer TP UL (kbps)                  float64
TCP DL Retrans. Vol (Bytes)              float64
TCP UL Retrans. Vol (Bytes)              float64
DL TP < 50 Kbps (%)                      float64
50 Kbps < DL TP < 250 Kbps (%)           float64
250 Kbps < DL TP < 1 Mbps (%)            float64
DL TP > 1 Mbps (%)                       float64
UL TP < 10 Kbps (%)                      float64
10 Kbps < UL TP < 50 Kbps (%)            float64
50 Kbps < UL TP < 300 Kbps (%)           float64
UL TP > 300 Kbps (%)                     float64
Activity Duration DL (ms)                float64
Activity Duration UL (ms)                float64
Dur (ms)                                 float64
Handset Manufacturer              string[python]
Handset Type                      string[python]
Nb of sec with Vol DL < 6250B            float64
Nb of sec with Vol UL < 1250B            float64
Social Media DL (Bytes)                  float64
Social Media UL (Bytes)                  float64
Google DL (Bytes)                        float64
Google UL (Bytes)                        float64
Email DL (Bytes)                         float64
Email UL (Bytes)                         float64
Youtube DL (Bytes)                       float64
Youtube UL (Bytes)                       float64
Netflix DL (Bytes)                       float64
Netflix UL (Bytes)                       float64
Gaming DL (Bytes)                        float64
Gaming UL (Bytes)                        float64
Other DL (Bytes)                         float64
Other UL (Bytes)                         float64
Total UL (Bytes)                         float64
Total DL (Bytes)                         float64
dtype: object

We also know that Bearer Id, IMSI, MSISDN / Number, and IMEI are unique numbers used for identification. Therefore, for better readability (and to facilitate the filters used in subsequent analyses), we will change their data types from float64 to int64.

In [450]:
# 68. List of columns for conversion
int_cols = ['Bearer Id', 'IMSI', 'MSISDN/Number', 'IMEI']

In [451]:
# 69. Function to convert columns to int
def convert_to_int(df, columns):
    for col in columns:
        df[col] = df[col].astype("int64")

In [452]:
# 70. Convert columns to int
convert_to_int(cleaned_dataset, int_cols)

In [453]:
# 71. Data types of each column in the cleaned dataframe
cleaned_dataset.dtypes

Bearer Id                                  int64
Start                             datetime64[ns]
Start Offset (ms)                        float64
End                               datetime64[ns]
End Offset (ms)                          float64
Dur (s)                                  float64
IMSI                                       int64
MSISDN/Number                              int64
IMEI                                       int64
Last Location Name                string[python]
Avg RTT DL (ms)                          float64
Avg RTT UL (ms)                          float64
Avg Bearer TP DL (kbps)                  float64
Avg Bearer TP UL (kbps)                  float64
TCP DL Retrans. Vol (Bytes)              float64
TCP UL Retrans. Vol (Bytes)              float64
DL TP < 50 Kbps (%)                      float64
50 Kbps < DL TP < 250 Kbps (%)           float64
250 Kbps < DL TP < 1 Mbps (%)            float64
DL TP > 1 Mbps (%)                       float64
UL TP < 10 Kbps (%)                      float64
10 Kbps < UL TP < 50 Kbps (%)            float64
50 Kbps < UL TP < 300 Kbps (%)           float64
UL TP > 300 Kbps (%)                     float64
Activity Duration DL (ms)                float64
Activity Duration UL (ms)                float64
Dur (ms)                                 float64
Handset Manufacturer              string[python]
Handset Type                      string[python]
Nb of sec with Vol DL < 6250B            float64
Nb of sec with Vol UL < 1250B            float64
Social Media DL (Bytes)                  float64
Social Media UL (Bytes)                  float64
Google DL (Bytes)                        float64
Google UL (Bytes)                        float64
Email DL (Bytes)                         float64
Email UL (Bytes)                         float64
Youtube DL (Bytes)                       float64
Youtube UL (Bytes)                       float64
Netflix DL (Bytes)                       float64
Netflix UL (Bytes)                       float64
Gaming DL (Bytes)                        float64
Gaming UL (Bytes)                        float64
Other DL (Bytes)                         float64
Other UL (Bytes)                         float64
Total UL (Bytes)                         float64
Total DL (Bytes)                         float64
dtype: object

In [454]:
# 72. Function to drop duplicate rows
def drop_duplicates(df):
    old = df.shape[0]
    df.drop_duplicates(inplace=True)
    new = df.shape[0]
    count = old - new
    if count == 0:
        print("No duplicate rows were found.")
    else:
        print(f"{count} duplicate rows were found and removed.")

In [455]:
# 73. Check for duplicate records and remove them if found
drop_duplicates(cleaned_dataset)

No duplicate rows were found.

As we saw in the column cleaning section, we have two duration columns, one in seconds and the other in microseconds. Let’s check if the values are equal by converting the microseconds to seconds.

In [456]:
# 74. Function to convert time unit
def convert_time_unit(df, columns, factor):
    for col in columns:
        df[col] = df[col] * factor

In [457]:
# 75. Return the rows of the two columns
temp_df = cleaned_dataset[['Dur (s)', 'Dur (ms)']].copy()

In [458]:
# 76. Display the first few rows of the temporary dataframe
temp_df.head()

     Dur (s)      Dur (ms)
0  1823652.0  1.823653e+09
1  1365104.0  1.365104e+09
2  1361762.0  1.361763e+09
3  1321509.0  1.321510e+09
4  1089009.0  1.089009e+09

In [459]:
# 77. Apply the function to convert microseconds to seconds
convert_time_unit(temp_df, ['Dur (ms)'], 1/1000)

In [460]:
# 78. Display the first few rows of the temporary dataframe after conversion
temp_df.head()

     Dur (s)     Dur (ms)
0  1823652.0  1823652.892
1  1365104.0  1365104.371
2  1361762.0  1361762.651
3  1321509.0  1321509.685
4  1089009.0  1089009.389

In [461]:
# 79. Comparison
temp_df['Comparison_Result'] = (temp_df['Dur (s)'] == temp_df['Dur (ms)'].apply(math.floor))

In [462]:
temp_df

          Dur (s)     Dur (ms)  Comparison_Result
0       1823652.0  1823652.892               True
1       1365104.0  1365104.371               True
2       1361762.0  1361762.651               True
3       1321509.0  1321509.685               True
4       1089009.0  1089009.389               True
...           ...          ...                ...
149991    61661.0    61661.729               True
149992    84940.0    84940.610               True
149993   125622.0   125622.433               True
149994   113545.0   113545.185               True
149995    59587.0    59587.792               True

[146887 rows x 3 columns]

In [463]:
# 80. Are the two columns equal?
print(all(temp_df['Comparison_Result']))

True

This proves that, when rounded, these two columns are equal. Therefore, we will keep “Dur (ms)” as it is more precise and remove “Dur (s)”.

In [464]:
# 81. Function to drop columns
def drop_columns(df, columns):
    df.drop(columns, axis=1, inplace=True)
    count = len(columns)
    if count == 1:
        print(f"{count} column was dropped.")
    else:
        print(f"{count} columns were dropped.")

In [465]:
# 82. Drop the column
drop_columns(cleaned_dataset, ['Dur (s)'])

1 column was dropped.

## **Step 3 - Outlier Treatment**

In [466]:

# 83. Display the image
# img = mpimg.imread('outliers.png')
# plt.imshow(img_dsa)
# plt.axis('off')
# plt.show()

In [467]:
# 84. Shape of the cleaned dataframe
cleaned_dataset.shape

(146887, 46)

In [468]:
# 85. Define the OutlierHandler class
class OutlierHandler:

    # Constructor that initializes with a DataFrame
    def __init__(self, df: pd.DataFrame) -> None:
        self.df = df

    # Function to count outliers in the specified columns
    def count_outliers(self, Q1, Q3, IQR, columns):

        # Define the cutoff limit for considering a value as an outlier
        cut_off = IQR * 1.5

        # Create a temporary DataFrame with boolean values indicating outliers
        temp_df = (self.df[columns] < (Q1 - cut_off)) | (self.df[columns] > (Q3 + cut_off))

        # Return the count of outliers for each column
        return [len(temp_df[temp_df[col] == True]) for col in temp_df]

    # Function to calculate skewness of the specified columns
    def calc_skew(self, columns=None):

        # If no columns are specified, use all columns of the DataFrame
        if columns is None:
            columns = self.df.columns

        # Return the skewness measure for each column
        return [self.df[col].skew() for col in columns]

    # Function to calculate the percentage of values relative to 146887 (number of rows so far)
    def percentage(self, values):
        return [str(round(((value / 146887) * 100), 2)) + '%' for value in values]

    # Function to remove outliers in the specified columns
    def remove_outliers(self, columns):
        for col in columns:

            # Calculate the Q1 and Q3 quantiles
            Q1, Q3 = self.df[col].quantile(0.25), self.df[col].quantile(0.75)

            # Calculate the interquartile range (IQR)
            IQR = Q3 - Q1

            # Define the limits for considering a value as an outlier
            cut_off = IQR * 1.5
            lower, upper = Q1 - cut_off, Q3 + cut_off

            # Remove values considered outliers
            self.df = self.df.drop(self.df[self.df[col] > upper].index)
            self.df = self.df.drop(self.df[self.df[col] < lower].index)

    # Function to replace outliers with the fence values in the specified columns
    def replace_outliers_with_fences(self, columns):
        for col in columns:

            # Calculate the Q1 and Q3 quantiles
            Q1, Q3 = self.df[col].quantile(0.25), self.df[col].quantile(0.75)

            # Calculate the interquartile range (IQR)
            IQR = Q3 - Q1

            # Define the limits for considering a value as an outlier
            cut_off = IQR * 1.5
            lower, upper = Q1 - cut_off, Q3 + cut_off

            # Replace outliers with the fence values
            self.df[col] = np.where(self.df[col] > upper, upper, self.df[col])
            self.df[col] = np.where(self.df[col] < lower, lower, self.df[col])

    # Function to obtain a statistical summary of the specified columns
    def get_overview(self, columns) -> None:

        # Calculate various statistics for the columns
        min_val = self.df[columns].min()
        Q1 = self.df[columns].quantile(0.25)
        median = self.df[columns].quantile(0.5)
        Q3 = self.df[columns].quantile(0.75)

        max_val = self.df[columns].max()
        IQR = Q3 - Q1
        skew = self.calc_skew(columns)
        outliers = self.count_outliers(Q1, Q3, IQR, columns)
        cut_off = IQR * 1.5
        lower, upper = Q1 - cut_off, Q3 + cut_off

        # Define the column names for the new DataFrame
        new_columns = ['Column Name',
                       'Min',
                       'Q1',
                       'Median',
                       'Q3',
                       'Max',
                       'IQR',
                       'Lower Fence',
                       'Upper Fence',
                       'Skew',
                       'Num_Outliers',
                       'Percent_Outliers']

        # Create a new DataFrame with the calculated statistics
        data = zip([column for column in self.df[columns]], min_val, Q1, median, Q3, max_val, IQR, lower, upper, skew, outliers, self.percentage(outliers))
        new_df = pd.DataFrame(data=data, columns=new_columns)

        # Set 'Column Name' as the index of the new DataFrame
        new_df.set_index('Column Name', inplace=True)

        # Return the new DataFrame sorted by the number of outliers
        return new_df.sort_values('Num_Outliers', ascending=False).transpose()

In [469]:
# 86. Create the outlier handler object
outlier_handler = OutlierHandler(cleaned_dataset)

In [470]:
# 87. List of columns with data type float64
float_columns = cleaned_dataset.select_dtypes('float64').columns.tolist()

In [471]:
float_columns

['Start Offset (ms)',
 'End Offset (ms)',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur (ms)',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

In [490]:
# 88. Overview of outliers
outlier_summary = outlier_handler.get_overview(float_columns)
outlier_summary

Column Name,Start Offset (ms),Nb of sec with Vol DL < 6250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Nb of sec with Vol UL < 1250B,Dur (ms),End Offset (ms),Activity Duration UL (ms),Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Total DL (Bytes)
Min,0.0,1.0,12.0,0.0,207.0,3.0,14.0,2.0,53.0,105.0,42.0,35.0,2516.0,59.0,3290.0,148.0,9493545.0,1.0,7142988.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,77.5,0.0,0.0,0.0,97.5,0.0,0.0,0.0,0.0,7114041.0
Q1,250.0,87.0,898089.0,16431.0,2882586.5,1024371.5,892573.0,233439.0,5833462.0,5516549.0,5776625.5,5480202.0,210381659.0,4132622.0,210155459.0,4144551.0,33218346.0,107.0,58526863.0,251.0,22073.0,31.0,2.0,43.0,47.0,24895.0,3299.5,91.0,0.0,0.0,0.0,99.0,0.0,0.0,0.0,15418.0,243073402.5
Median,499.0,201.0,1793409.0,32908.0,5766724.0,2054793.0,1793613.0,466357.0,11616334.0,11013447.0,11642708.0,10999348.0,423492394.0,8294516.0,421633232.0,8265817.0,41143144.0,217.0,86399988.0,500.0,47180.0,44.0,5.0,64.0,63.0,391635.0,16436.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,39726.0,455963875.0
Q3,749.0,2612.5,2694640.0,49326.5,8625551.0,3088071.5,2689818.0,700297.5,17440635.5,16514278.0,17469653.0,16503222.5,633333998.5,12432390.5,631361047.5,12382039.5,49034880.0,2466.5,133159382.0,750.0,611803.0,67.0,13.0,20024.0,1136.0,3078146.0,68622.0,100.0,4.0,1.0,0.0,100.0,0.0,0.0,0.0,697298.5,665783068.0
Max,999.0,6400.75,3586064.0,65870.0,11462832.0,4121357.0,3586146.0,936418.0,23259098.0,22011962.0,23259189.0,22011955.0,843441889.0,16558794.0,843442489.0,16558816.0,72759681.0,6005.75,245108160.5,999.0,1496398.0,121.0,29.5,49995.5,2769.5,7658022.5,166605.75,100.0,10.0,2.5,0.0,100.0,0.0,0.0,0.0,1720119.25,902969616.0
IQR,499.0,2525.5,1796551.0,32895.5,5742964.5,2063700.0,1797245.0,466858.5,11607173.5,10997729.0,11693027.5,11023020.5,422952339.5,8299768.5,421205588.5,8237488.5,15816534.0,2359.5,74632519.0,499.0,589730.0,36.0,11.0,19981.0,1089.0,3053251.0,65322.5,9.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,681880.5,422709665.5
Lower Fence,-498.5,-3701.25,-1796737.5,-32912.25,-5731860.25,-2071178.5,-1803294.5,-466848.75,-11577298.25,-10980044.5,-11762915.75,-11054328.75,-424046850.25,-8317030.75,-421652923.75,-8211681.75,9493545.0,-3432.25,-53421915.5,-497.5,-862522.0,-23.0,-14.5,-29928.5,-1586.5,-4554981.5,-94684.25,77.5,-6.0,-1.5,0.0,97.5,0.0,0.0,0.0,-1007402.75,-390991095.75
Upper Fence,1497.5,6400.75,5389466.5,98669.75,17239997.75,6183621.5,5385685.5,1400585.25,34851395.75,33010871.5,35009194.25,33037753.25,1267762507.75,24882043.25,1263169430.25,24738272.25,72759681.0,6005.75,245108160.5,1498.5,1496398.0,121.0,29.5,49995.5,2769.5,7658022.5,166605.75,113.5,10.0,2.5,0.0,101.5,0.0,0.0,0.0,1720119.25,1299847566.25
Skew,0.000823,1.205814,-0.001633,0.000258,-0.008414,0.002242,-0.002659,0.007312,0.000119,-0.001265,-0.002172,-0.000273,-0.003914,-0.002566,0.001832,0.001481,-0.001978,1.209533,0.810422,-0.001251,1.207483,1.069479,1.165443,1.280613,1.230407,1.216388,1.20234,-1.22817,1.315047,1.098748,0.0,-0.947267,0.0,0.0,0.0,1.205281,-0.003579
Num_Outliers,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Percent_Outliers,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%

In [473]:
# 89. Replace outliers with the fence values
outlier_handler.replace_outliers_with_fences(float_columns)

In [474]:
# 90. Overview of outliers after replacement
outlier_summary_updated = outlier_handler.get_overview(float_columns)

## **Delivering the Results of the Analysis to Decision Makers**

Is having the sum of the upload and download data volumes for each application as a total necessary for analyses?

In [475]:
# 91. Calculate the total social media data volume
cleaned_dataset['Social Media Data Volume (Bytes)'] = cleaned_dataset['Social Media UL (Bytes)'] + cleaned_dataset['Social Media DL (Bytes)']

In [476]:
# 92. Calculate the total Google data volume
cleaned_dataset['Google Data Volume (Bytes)'] = cleaned_dataset['Google UL (Bytes)'] + cleaned_dataset['Google DL (Bytes)']

In [477]:
# 93. Calculate the total Email data volume
cleaned_dataset['Email Data Volume (Bytes)'] = cleaned_dataset['Email UL (Bytes)'] + cleaned_dataset['Email DL (Bytes)']

In [478]:
# 94. Calculate the total YouTube data volume
cleaned_dataset['Youtube Data Volume (Bytes)'] = cleaned_dataset['Youtube UL (Bytes)'] + cleaned_dataset['Youtube DL (Bytes)']

In [479]:
# 95. Calculate the total Netflix data volume
cleaned_dataset['Netflix Data Volume (Bytes)'] = cleaned_dataset['Netflix UL (Bytes)'] + cleaned_dataset['Netflix DL (Bytes)']

In [480]:
# 96. Calculate the total Gaming data volume
cleaned_dataset['Gaming Data Volume (Bytes)'] = cleaned_dataset['Gaming UL (Bytes)'] + cleaned_dataset['Gaming DL (Bytes)']

In [481]:
# 97. Calculate the total Other data volume
cleaned_dataset['Other Data Volume (Bytes)'] = cleaned_dataset['Other UL (Bytes)'] + cleaned_dataset['Other DL (Bytes)']

In [482]:
# 98. Calculate the total data volume
cleaned_dataset['Total Data Volume (Bytes)'] = cleaned_dataset['Total UL (Bytes)'] + cleaned_dataset['Total DL (Bytes)']

In [483]:
# 99. Information about the cleaned dataframe
cleaned_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146887 entries, 0 to 149995
Data columns (total 54 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Bearer Id                         146887 non-null  int64
 1   Start                             146887 non-null  datetime64[ns]
 2   Start Offset (ms)                 146887 non-null  float64
 3   End                               146887 non-null  datetime64[ns]
 4   End Offset (ms)                   146887 non-null  float64
 5   IMSI                              146887 non-null  int64
 6   MSISDN/Number                     146887 non-null  int64
 7   IMEI                              146887 non-null  int64
 8   Last Location Name                146887 non-null  string
 9   Avg RTT DL (ms)                   146887 non-null  float64
 10  Avg RTT UL (ms)                   146887 non-null  float64
 11  Avg Bearer TP DL (kbps)           146887 non-null  float64
 12  Avg Bearer TP UL (kbps)           146887 non-null  float64
 13  TCP DL Retrans. Vol (Bytes)       146887 non-null  float64
 14  TCP UL Retrans. Vol (Bytes)       146887 non-null  float64
 15  DL TP < 50 Kbps (%)               146887 non-null  float64
 16  50 Kbps < DL TP < 250 Kbps (%)    146887 non-null  float64
 17  250 Kbps < DL TP < 1 Mbps (%)     146887 non-null  float64
 18  DL TP > 1 Mbps (%)                146887 non-null  float64
 19  UL TP < 10 Kbps (%)               146887 non-null  float64
 20  10 Kbps < UL TP < 50 Kbps (%)     146887 non-null  float64
 21  50 Kbps < UL TP < 300 Kbps (%)    146887 non-null  float64
 22  UL TP > 300 Kbps (%)              146887 non-null  float64
 23  Activity Duration DL (ms)         146887 non-null  float64
 24  Activity Duration UL (ms)         146887 non-null  float64
 25  Dur (ms)                          146887 non-null  float64
 26  Handset Manufacturer              146887 non-null  string
 27  Handset Type                      146887 non-null  string
 28  Nb of sec with Vol DL < 6250B     146887 non-null  float64
 29  Nb of sec with Vol UL < 1250B     146887 non-null  float64
 30  Social Media DL (Bytes)           146887 non-null  float64
 31  Social Media UL (Bytes)           146887 non-null  float64
 32  Google DL (Bytes)                 146887 non-null  float64
 33  Google UL (Bytes)                 146887 non-null  float64
 34  Email DL (Bytes)                  146887 non-null  float64
 35  Email UL (Bytes)                  146887 non-null  float64
 36  Youtube DL (Bytes)                146887 non-null  float64
 37  Youtube UL (Bytes)                146887 non-null  float64
 38  Netflix DL (Bytes)                146887 non-null  float64
 39  Netflix UL (Bytes)                146887 non-null  float64
 40  Gaming DL (Bytes)                 146887 non-null  float64
 41  Gaming UL (Bytes)                 146887 non-null  float64
 42  Other DL (Bytes)                  146887 non-null  float64
 43  Other UL (Bytes)                  146887 non-null  float64
 44  Total UL (Bytes)                  146887 non-null  float64
 45  Total DL (Bytes)                  146887 non-null  float64
 46  Social Media Data Volume (Bytes)  146887 non-null  float64
 47  Google Data Volume (Bytes)        146887 non-null  float64
 48  Email Data Volume (Bytes)         146887 non-null  float64
 49  Youtube Data Volume (Bytes)       146887 non-null  float64
 50  Netflix Data Volume (Bytes)       146887 non-null  float64
 51  Gaming Data Volume (Bytes)        146887 non-null  float64
 52  Other Data Volume (Bytes)         146887 non-null  float64
 53  Total Data Volume (Bytes)         146887 non-null  float64
dtypes: datetime64[ns](2), float64(45), int64(4), string(3)
memory usage: 61.6 MB

In [484]:
# 100. Shape of the cleaned dataframe
cleaned_dataset.shape

(146887, 54)

In [485]:
# 101. Display the first few rows of the cleaned dataframe
cleaned_dataset.head()

,Bearer Id,Start,Start Offset (ms),End,End Offset (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Dur (ms),Handset Manufacturer,Handset Type,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes),Social Media Data Volume (Bytes),Google Data Volume (Bytes),Email Data Volume (Bytes),Youtube Data Volume (Bytes),Netflix Data Volume (Bytes),Gaming Data Volume (Bytes),Other Data Volume (Bytes),Total Data Volume (Bytes)
0,-9223372036854775808,2019-04-04 12:01:00,770.0,2019-04-25 14:35:00,662.0,208201448079117,33664962239,35521209507511,9.16456699548519E+015,42.0,5.0,23.0,44.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,37624.0,38787.0,245108160.5,Samsung,Samsung Galaxy A5 Sm-A520F,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0,1570185.0,2905912.0,3701304.0,18355943.0,17855187.0,292426453.0,180558843.0,345629377.0
1,-9223372036854775808,2019-04-09 13:04:00,235.0,2019-04-25 08:15:00,606.0,208201909211140,33681854413,35794009006359,L77566A,65.0,5.0,16.0,26.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,168.0,3560.0,245108160.5,Samsung,Samsung Galaxy J5 (Sm-J530),971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0,1933278.0,4414096.0,937385.0,39359124.0,35565545.0,609920783.0,541959383.0,707185356.0
2,-9223372036854775808,2019-04-09 17:42:00,1.0,2019-04-25 11:58:00,652.0,208200314458056,33760627129,35281510359387,D42335A,65.0,5.0,6.0,9.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,245108160.5,Samsung,Samsung Galaxy A8 (2018),751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0,1726277.0,10229119.0,3363124.0,34425237.0,23751202.0,229980251.0,414908351.0,307690973.0
3,-9223372036854775808,2019-04-10 00:31:00,486.0,2019-04-25 07:36:00,171.0,208201402342131,33750343200,35356610164913,T21824A,65.0,5.0,44.0,44.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,3330.0,37882.0,245108160.5,unknown,unknown,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0,657493.0,11811761.0,2070983.0,36534765.0,15092588.0,810387875.0,761837216.0,889352748.0
4,-9223372036854775808,2019-04-12 20:10:00,565.0,2019-04-25 10:40:00,954.0,208201401415120,33699795932,35407009745539,D88865A,65.0,5.0,6.0,9.0,19520.0,7230.0,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,245108160.5,Samsung,Samsung Sm-G390F,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0,912788.0,7748843.0,2110349.0,34222253.0,17539799.0,531237049.0,564619822.0,607681403.0

## **Saving the Data After Cleaning**

In [486]:
# 102. Saving the cleaned data
cleaned_dataset.to_csv('cleaned_dataset.csv', index=False)

In [487]:
%watermark -a "panData"

Author: panData

In [488]:
%watermark

Last updated: 2024-11-06T06:31:25.117307+00:00

Python implementation: CPython
Python version       : 3.10.12
IPython version      : 7.34.0

Compiler    : GCC 11.4.0
OS          : Linux
Release     : 6.1.85+
Machine     : x86_64
Processor   : x86_64
CPU cores   : 2
Architecture: 64bit

In [489]:
%watermark --iversions

pandas    : 2.2.2
sys       : 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
numpy     : 1.26.4
matplotlib: 3.8.0

# **The End**